name: Generate List

on:
  push:
    branches: 
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: update list
      run: |
        bash ./gen_list.sh

    - name: commit list
      run: |
        git add -A
        git diff HEAD --exit-code
        if ($LASTEXITCODE -eq 0) {
          Write-Host "No changes to commit!"
        } else {
          git config --global user.name "william[bot]"
          git config --global user.email "gw826943555@qq.com"
          git commit -m "Updated list on $(date -I)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin master
        }
